name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
                         
    env:
      Solution_Name: MVVMBase.sln                               

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Add Source
      run: dotnet nuget add source --username HenryGeorgist --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/HenryGeorgist/index.json"
      
    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Debug

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=Debug


    - name: Pack 
      run: |
            $datetime = get-date -f yyyy.M.d.Hmm
            $versionSuffix = "alpha-" + $datetime
            dotnet pack --configuration Release --version-suffix $versionSuffix
      shell: powershell
    
    - name: Publish
      run: |
            dotnet nuget push "D:\a\Framework\Framework\Output\HenryGeorgist.Framework.View*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
            dotnet nuget push "D:\a\Framework\Framework\Output\HenryGeorgist.Framework.Model*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
            dotnet nuget push "D:\a\Framework\Framework\Output\HenryGeorgist.Framework.ViewModel*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
            dotnet nuget push "D:\a\Framework\Framework\Output\HenryGeorgist.Framework.Base*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate





  
